name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-docker-buildx@126d331dc69f4a1aa02452e374835e6a5d565613
      uses: crazy-max/ghaction-docker-buildx@v3.3.1
      with:
        # Buildx version. Example: v0.3.0
        buildx-version: latest # optional, default is latest
        # QEMU static binaries Docker image version. Example: 4.2.0-7
        qemu-version: latest # optional, default is latest
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secret.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker buildX BUILD --push --tag ragnaro/dhcp:latest --platform linux/arm64 .
